"""initial evidence and coverage schema

Revision ID: 34b922b66c1c
Revises:
Create Date: 2026-10-03 16:35:15.066380

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34b922b66c1c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jurisdictions",
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "nationwide_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("manifest", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "research_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("request_json", sa.JSON(), nullable=False),
        sa.Column("graph_version", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("publisher", sa.String(length=255), nullable=True),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("authority_tier", sa.Integer(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_url"),
    )
    op.create_table(
        "trades",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "coverage_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("primary_jurisdiction", sa.String(length=8), nullable=False),
        sa.Column("locality_key", sa.String(length=255), nullable=False),
        sa.Column("trade", sa.String(length=64), nullable=False),
        sa.Column("credential_key", sa.String(length=80), nullable=False),
        sa.Column("effective_date_key", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("research_run_id", sa.String(length=36), nullable=True),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("authoritative_source_count", sa.Integer(), nullable=False),
        sa.Column("unresolved_field_count", sa.Integer(), nullable=False),
        sa.Column("last_attempted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_reason", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["primary_jurisdiction"],
            ["jurisdictions.code"],
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trade"],
            ["trades.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "primary_jurisdiction", "locality_key", "trade", "credential_key", "effective_date_key"
        ),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("raw_artifact_path", sa.Text(), nullable=False),
        sa.Column("extracted_text", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("resolved_url", sa.Text(), nullable=False),
        sa.Column("etag", sa.Text(), nullable=True),
        sa.Column("last_modified", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "content_sha256"),
    )
    op.create_table(
        "regulatory_authorities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("official_url", sa.Text(), nullable=True),
        sa.Column("jurisdiction_code", sa.String(length=8), nullable=True),
        sa.ForeignKeyConstraint(
            ["jurisdiction_code"],
            ["jurisdictions.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "requirement_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("research_run_id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_json", sa.JSON(), nullable=False),
        sa.Column("research_status", sa.String(length=32), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("research_run_id"),
    )
    op.create_table(
        "review_actions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("research_run_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("reviewer", sa.String(length=255), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "validation_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("research_run_id", sa.String(length=36), nullable=False),
        sa.Column("check_name", sa.String(length=80), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "change_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("previous_version_id", sa.String(length=36), nullable=True),
        sa.Column("new_version_id", sa.String(length=36), nullable=False),
        sa.Column("field_path", sa.String(length=255), nullable=False),
        sa.Column("old_value", sa.JSON(), nullable=True),
        sa.Column("new_value", sa.JSON(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["new_version_id"],
            ["requirement_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_version_id"],
            ["requirement_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "claims",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("requirement_version_id", sa.String(length=36), nullable=False),
        sa.Column("field_path", sa.String(length=255), nullable=False),
        sa.Column("value_json", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["requirement_version_id"],
            ["requirement_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conflicts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("requirement_version_id", sa.String(length=36), nullable=False),
        sa.Column("field_path", sa.String(length=255), nullable=False),
        sa.Column("competing_claims", sa.JSON(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["requirement_version_id"],
            ["requirement_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "credentials",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("jurisdiction_code", sa.String(length=8), nullable=False),
        sa.Column("locality", sa.String(length=255), nullable=True),
        sa.Column("trade", sa.String(length=64), nullable=False),
        sa.Column("official_title", sa.String(length=255), nullable=False),
        sa.Column("canonical_level", sa.String(length=80), nullable=True),
        sa.Column("authority_id", sa.String(length=36), nullable=True),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["authority_id"],
            ["regulatory_authorities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["jurisdiction_code"],
            ["jurisdictions.code"],
        ),
        sa.ForeignKeyConstraint(
            ["trade"],
            ["trades.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evidence_spans",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("field_path", sa.String(length=255), nullable=False),
        sa.Column("quoted_text", sa.Text(), nullable=False),
        sa.Column("text_start", sa.Integer(), nullable=True),
        sa.Column("text_end", sa.Integer(), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("section", sa.String(length=255), nullable=True),
        sa.Column("asserted_value_json", sa.JSON(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "retrieval_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "claim_evidence",
        sa.Column("claim_id", sa.String(length=36), nullable=False),
        sa.Column("evidence_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence_spans.id"],
        ),
        sa.PrimaryKeyConstraint("claim_id", "evidence_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("claim_evidence")
    op.drop_table("retrieval_events")
    op.drop_table("evidence_spans")
    op.drop_table("credentials")
    op.drop_table("conflicts")
    op.drop_table("claims")
    op.drop_table("change_events")
    op.drop_table("validation_results")
    op.drop_table("review_actions")
    op.drop_table("requirement_versions")
    op.drop_table("regulatory_authorities")
    op.drop_table("documents")
    op.drop_table("coverage_records")
    op.drop_table("trades")
    op.drop_table("sources")
    op.drop_table("research_runs")
    op.drop_table("nationwide_runs")
    op.drop_table("jurisdictions")
    # ### end Alembic commands ###
