"""require scope audits for completion

Revision ID: 7608c288dc5a
Revises: 34b922b66c1c
Create Date: 2026-10-03 16:40:16.485676

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7608c288dc5a"
down_revision: str | Sequence[str] | None = "34b922b66c1c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "nationwide_runs",
        sa.Column(
            "primary_inventory_audited", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "nationwide_runs",
        sa.Column(
            "credential_levels_audited", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "nationwide_runs",
        sa.Column(
            "locality_expansion_audited", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "nationwide_runs",
        sa.Column("federal_overlays_audited", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nationwide_runs", "federal_overlays_audited")
    op.drop_column("nationwide_runs", "locality_expansion_audited")
    op.drop_column("nationwide_runs", "credential_levels_audited")
    op.drop_column("nationwide_runs", "primary_inventory_audited")
    # ### end Alembic commands ###
