"""national jobs and federal overlay queue

Revision ID: 7890c622ed95
Revises: 7608c288dc5a
Create Date: 2026-10-03 17:01:01.185050

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7890c622ed95"
down_revision: str | Sequence[str] | None = "7608c288dc5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "national_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("nationwide_run_id", sa.String(length=36), nullable=False),
        sa.Column("jurisdiction_code", sa.String(length=8), nullable=False),
        sa.Column("locality_key", sa.String(length=255), nullable=False),
        sa.Column("trade", sa.String(length=64), nullable=False),
        sa.Column("credential_key", sa.String(length=80), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("source_urls", sa.JSON(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_attempted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("research_run_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["jurisdiction_code"],
            ["jurisdictions.code"],
        ),
        sa.ForeignKeyConstraint(
            ["nationwide_run_id"],
            ["nationwide_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trade"],
            ["trades.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "nationwide_run_id",
            "jurisdiction_code",
            "locality_key",
            "trade",
            "credential_key",
            "stage",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("national_jobs")
    # ### end Alembic commands ###
